# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://43.142.156.160:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: 190804
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url: 
                username: 
                password: 
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: ruoyi
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

--- # sms 短信发送
sms:
    enabled: true
    endpoint: "sms.tencentcloudapi.com"
    accessKeyId: AKIDLZaNzSmhT8d0A6xfASWLwKUPo01oNgke
    accessKeySecret: iDUZQDl5C4jBQQBi393kHclgUBfx3weD
    signName: kamden博网
    # 腾讯专用
    sdkAppId: 1400758208

--- # mail 邮件发送
mail:
    enabled: true
    host: smtp.163.com
    port: 465
    # 是否需要用户名密码验证
    auth: true
    # 发送方，遵循RFC-822标准
    from: jasonkamden@163.com
    # 用户名（注意：如果使用foxmail邮箱，此处user为qq号）
    user: jasonkamden@163.com
    # 密码（注意，某些邮箱需要为SMTP服务单独设置密码，详情查看相关帮助）
    pass: MXBVCBPOYHRLVIJK
    # 使用 STARTTLS安全连接，STARTTLS是对纯文本通信协议的扩展。
    starttlsEnable: true
    # 使用SSL安全连接
    sslEnable: true
    # SMTP超时时长，单位毫秒，缺省值不超时
    timeout: 0
    # Socket连接超时值，单位毫秒，缺省值不超时
    connectionTimeout: 0